version: "3.7"

services:
  app:
    build: syncvm
    container_name: syncvm-release
    restart: always
    env_file:
      - django.env
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/src/staticfiles
    command:
      "gunicorn --workers=4 --bind=0.0.0.0:8080 syncvmsite.wsgi:application"
  
  nginx:
    image: nginx:1.17
    container_name: syncvm-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/src/staticfiles
    depends_on:
      - app

volumes:
  static_volume:
