version: "3.7"

services:
  app:
    build: syncvm
    container_name: syncvm-release
    restart: always
    env_file:
      - django.env
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/src/staticfiles
    command:
      "gunicorn --workers=4 --bind=0.0.0.0:8080 syncvmsite.wsgi:application"
    depends_on:
      - syncvm_database1
  
  nginx:
    image: nginx:1.17
    container_name: syncvm-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/src/staticfiles
    depends_on:
      - app

  syncvm_database1:
    image: postgres:10
    container_name: syncvm-db1
    env_file:
      - syncvm_database1.env
    ports:
      - "5432:5432"
    volumes:
      - syncvm_database1_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  syncvm_database1_volume:
  
